Parameters:
  OfficeIp:
    Type: String
    Default: 0.0.0.0/0
    Description: Enter the CIDR for the office IP
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcID in which you wish to deploy the EKS cluster
  ClusterName:
    Type: String
    Description: Name of your EKS Cluster
  Subnets:
    Type: "List<AWS::EC2::SecurityGroup::Id>"
    Description: List of subnets to use in your cluster

Resources:
  ControlPlaneSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref VpcId
      GroupName: eks-control-plane-sg
      GroupDescription: Control Plane Security Group
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: !Ref OfficeIp
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0 

  EksCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      Version: "1.10"
      RoleArn: !GetAtt EKSServiceRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds: [!GetAtt ControlPlaneSecurityGroup.GroupId]
        SubnetIds: [!Ref Subnets]

  IngressSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref VpcId
      GroupName: alb-ingress-sg
      GroupDescription: Allow Traffic from Office/VPN
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: !Ref OfficeIp
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0

  EKSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: EKSServiceRole

  ServiceLinkedRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "arn:aws:iam::001764686859:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing"
          }
        ]
      }
      PolicyName: CreateServiceLinkedRole-k8s
      Roles:
        - EKSServiceRole

Outputs:
  AlbIngressSecurityGroupId:
    Description: "SecurityGroup Id for ALB Ingress"
    Value: !GetAtt IngressSecurityGroup.GroupId
    Export:
      Name: alb-ingress-sg