AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS - IAM Service Role'

Resources:
  EKSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: EKSServiceRole

  ServiceLinkedRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "arn:aws:iam::001764686859:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing"
          }
        ]
      }
      PolicyName: CreateServiceLinkedRole-k8s
      Roles:
        - EKSServiceRole

