apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::001764686859:user/marc.wensauer
      username: marc.wensauer
      groups:
        - "system:masters"
    - userarn: arn:aws:iam::001764686859:user/todd.howson
      username: todd.howson
      groups:
        - "system:masters"
  mapRoles: |
    - rolearn: arn:aws:iam::001764686859:role/Hackathon-WorkerNodes-NodeInstanceRole-65W6P0DSY3H6
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - "system:bootstrappers"
        - "system:nodes"