apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::XXXXXXXXXXXX:user/first.last
      username: first.last
      groups:
        - "system:masters"
  mapRoles: |
    - rolearn: arn:aws:iam::XXXXXXXX:role/Hackathon-WorkerNodes-NodeInstanceRole-65W6P0DSY3H6
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - "system:bootstrappers"
        - "system:nodes"