AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a bastion & Security Group
Parameters:
  OfficeIp:
    Type: String
    Description: Enter the CIDR for the office IP
  VpcId:
    Type: String
    Description: VpcID you want to deploy bastion in
  KeyPair:
    Type: String
    Description: SSH Key Pair to access bastion
  AMI:
    Type: String
    Description: AMI to use for bastion
    Default: ami-a9d09ed1
  SubnetId:
    Type: String
    Decription: Subnet to deploy bastion in
Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref AMI
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
          - !Ref BastionSecurityGroup
          SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: Value
  BastionSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref VpcId
      GroupName: Bastion-SG
      GroupDescription: Allow SSH from Office/VPN
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref OfficeIp
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0