#cloud-config
cloud_final_modules:
- [users-groups,always]
users:
  - name: kody.trinnier
    groups: [ wheel ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNucuZO3lOpC7ZmEsdyYF54PzTHvNNeA1SxbppNogkDqN0F3bgx9omHxEBGf9rdmBDeI2Jw3J/WUSvvhetcOGpVh5yONGh9ZyrPRMciO6N9CElZAior6gUyWHookBLzWSG4aoZPg7SOQXzVf76llazKgt8tFPe/3roNKRFk5ntqW0yNTvgPzrRBwJIn59OzFzv29dx7v/uElP0GKHVRTkYuyApAp0KfJUGAUDV2Erwb4UOU+/2szOkBZK3RTbT/ctnAVpYRirdYh/sq0otwAeWqNytEGxmGHK2xgmiYqHRevwqmTJ5yX+P8W1OCoBABwI9CPLKXAdgV8XfPJto+eU/ kody.trinnier@1360-MBP.local"
